# -*- coding: utf-8 -*-

from builtins import object
from PyQt5.QtWidgets import QTabWidget, QWidget, QGroupBox, QLabel, QComboBox, QPushButton, QCheckBox
from PyQt5.QtWidgets import QTextBrowser, QPlainTextEdit, QLineEdit, QToolButton, QApplication
from PyQt5.QtCore import QRect, QMetaObject
from PyQt5.QtGui import QFont
from qgis._gui import QgsAuthConfigSelect

_fromUtf8 = lambda s: s


class Ui_WCPSClient(object):
    def setupUi(self, WCPSClient):
        WCPSClient.setObjectName(_fromUtf8("WCPSClient"))
        WCPSClient.resize(675, 518)
        self.tabWidget_WCPSClient = QTabWidget(WCPSClient)
        self.tabWidget_WCPSClient.setGeometry(QRect(10, 10, 675, 518))
        self.tabWidget_WCPSClient.setObjectName(_fromUtf8("tabWidget_WCPSClient"))
        self.tab_Serv = QWidget()
        self.tab_Serv.setGeometry(10, 10, 641, 471)
        self.tab_Serv.setObjectName(_fromUtf8("tab_Serv"))
        self.groupBox = QGroupBox(self.tab_Serv)
        self.groupBox.setGeometry(QRect(10, 20, 611, 101))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.cmbConnections_Serv = QComboBox(self.groupBox)
        self.cmbConnections_Serv.setGeometry(QRect(10, 30, 591, 31))
        self.cmbConnections_Serv.setObjectName(_fromUtf8("cmbConnections_Serv"))
        self.btnConnectServer_Serv = QPushButton(self.groupBox)
        self.btnConnectServer_Serv.setGeometry(QRect(130, 70, 111, 28))
        self.btnConnectServer_Serv.setObjectName(_fromUtf8("btnConnectServer_Serv"))
        self.btnNew_Serv = QPushButton(self.groupBox)
        self.btnNew_Serv.setGeometry(QRect(250, 70, 111, 28))
        self.btnNew_Serv.setObjectName(_fromUtf8("btnNew_Serv"))
        self.btnEdit_Serv = QPushButton(self.groupBox)
        self.btnEdit_Serv.setGeometry(QRect(370, 70, 111, 28))
        self.btnEdit_Serv.setObjectName(_fromUtf8("btnEdit_Serv"))
        self.btnDelete_Serv = QPushButton(self.groupBox)
        self.btnDelete_Serv.setGeometry(QRect(490, 70, 111, 28))
        self.btnDelete_Serv.setObjectName(_fromUtf8("btnDelete_Serv"))
        self.label_2 = QLabel(self.tab_Serv)
        self.label_2.setGeometry(QRect(10, 130, 601, 31))
        font = QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.textBrowser_Serv = QTextBrowser(self.tab_Serv)
        self.textBrowser_Serv.setGeometry(QRect(5, 161, 621, 81))
        self.textBrowser_Serv.setObjectName(_fromUtf8("textBrowser_Serv"))
        self.btnClose_Serv = QPushButton(self.tab_Serv)
        self.btnClose_Serv.setGeometry(QRect(520, 410, 93, 28))
        self.btnClose_Serv.setObjectName(_fromUtf8("btnClose_Serv"))
        self.groupBox_3 = QGroupBox(self.tab_Serv)
        self.groupBox_3.setGeometry(QRect(10, 250, 611, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setGeometry(QRect(10, 30, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QLabel(self.groupBox_3)
        self.label_4.setGeometry(QRect(10, 60, 171, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.UserNameLine = QLineEdit(self.groupBox_3)
        self.UserNameLine.setGeometry(QRect(80, 30, 511, 22))
        self.UserNameLine.setObjectName(_fromUtf8("UserNameLine"))
        self.PasswordLine = QLineEdit(self.groupBox_3)
        self.PasswordLine.setGeometry(QRect(80, 60, 511, 22))
        self.PasswordLine.setObjectName(_fromUtf8("PasswordLine"))
        self.tabWidget_WCPSClient.addTab(self.tab_Serv, _fromUtf8(""))
        self.tab_PC = QWidget()
        self.tab_PC.setEnabled(False)
        self.tab_PC.setGeometry(QRect(10, 10, 675, 518))
        self.tab_PC.setObjectName(_fromUtf8("tab_PC"))
        self.groupBox_2 = QGroupBox(self.tab_PC)
        self.groupBox_2.setGeometry(QRect(10, 10, 621, 401))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.plainTextEdit_PC = QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_PC.setGeometry(QRect(10, 30, 601, 361))
        self.plainTextEdit_PC.setObjectName(_fromUtf8("plainTextEdit_PC"))
        self.pushButton_PC = QPushButton(self.tab_PC)
        self.pushButton_PC.setGeometry(QRect(400, 420, 111, 28))
        self.pushButton_PC.setObjectName(_fromUtf8("pushButton_PC"))
        self.btnClose_PC = QPushButton(self.tab_PC)
        self.btnClose_PC.setGeometry(QRect(520, 420, 111, 28))
        self.btnClose_PC.setObjectName(_fromUtf8("btnClose_PC"))
        self.btnLoad_Query = QPushButton(self.tab_PC)
        self.btnLoad_Query.setGeometry(QRect(280, 420, 111, 28))
        self.btnLoad_Query.setObjectName(_fromUtf8("btnSave_Result"))
        self.tabWidget_WCPSClient.addTab(self.tab_PC, _fromUtf8(""))
        self.btnStore_Query = QPushButton(self.tab_PC)
        self.btnStore_Query.setGeometry(QRect(162, 420, 111, 28))
        self.btnStore_Query.setObjectName(_fromUtf8("btnSave_Result"))
        self.retranslateUi(WCPSClient)
        self.tabWidget_WCPSClient.setCurrentIndex(2)

        self.btnClose_Serv.clicked.connect(WCPSClient.close)
        self.btnClose_PC.clicked.connect(WCPSClient.close)
        self.btnConnectServer_Serv.clicked.connect(WCPSClient.connectServer)
        self.btnNew_Serv.clicked.connect(WCPSClient.newServer)
        self.btnEdit_Serv.clicked.connect(WCPSClient.editServer)
        self.btnDelete_Serv.clicked.connect(WCPSClient.deleteServer)
        self.pushButton_PC.clicked.connect(WCPSClient.exeProcessCoverage)
        self.btnLoad_Query.clicked.connect(WCPSClient.loadQuery)
        self.btnStore_Query.clicked.connect(WCPSClient.storeQuery)

        QMetaObject.connectSlotsByName(WCPSClient)

    def retranslateUi(self, WCPSClient):
        WCPSClient.setWindowTitle(QApplication.translate("WCPSClient", "WCPS datacube query", None))
        self.groupBox.setTitle(QApplication.translate("WCPSClient", "Server Connections:", None))
        self.btnConnectServer_Serv.setText(QApplication.translate("WCPSClient", "Connect", None))
        self.btnNew_Serv.setText(QApplication.translate("WCPSClient", "New", None))
        self.btnEdit_Serv.setText(QApplication.translate("WCPSClient", "Edit", None))
        self.btnDelete_Serv.setText(QApplication.translate("WCPSClient", "Delete", None))
        self.label_2.setText(QApplication.translate("WCPSClient", "Log", None))
        self.groupBox_3.setTitle(QApplication.translate("WCPSClient", "Authentication", None))
        self.label_3.setText(QApplication.translate("WCPSClient", "Username", None))
        self.label_4.setText(QApplication.translate("WCPSClient", "Password", None))
        self.btnClose_Serv.setText(QApplication.translate("WCPSClient", "Close", None))
        self.tabWidget_WCPSClient.setTabText(self.tabWidget_WCPSClient.indexOf(self.tab_Serv),
                                             QApplication.translate("WCPSClient", "Server", None))
        self.groupBox_2.setTitle(QApplication.translate("WCPSClient", "Queries Text ", None))
        self.pushButton_PC.setText(QApplication.translate("WCPSClient", "Submit", None))
        self.btnClose_PC.setText(QApplication.translate("WCPSClient", "Close", None))
        self.btnLoad_Query.setText(QApplication.translate("WCPSClient", "Load Query", None))
        self.tabWidget_WCPSClient.setTabText(self.tabWidget_WCPSClient.indexOf(self.tab_PC),
                                             QApplication.translate("WCPSClient", "WCPS query editor", None))
        self.btnStore_Query.setText(QApplication.translate("WCPSClient", "Store Query", None))
